name: CI
on: [ push ]

jobs:
  build_sovler_application:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@master

        - name: Building solver_application
          shell: bash
          working-directory: solver_application
          run: |
            cmake -B ./build
            cd build
            make
            ./question
        - name: packaging solver_application
          shell: bash
          working-directory: solver_application
          run: |
            cd build
            make package
            make package_source
